### ISSUE TITLE
Crash at Crafting Terminal when searching for an item

### ISSUE THREAD

**Issue by WimpieRatte** [tom5454/Toms-Storage#199]
Getting an error when I tried searching for an item.
java.lang.NullPointerException: Cannot assign field "field_22764" because "this.nextPageButton" is null
	at net.minecraft.class_507.updatePageSwitchButtons(class_507.java:4771)
	at net.minecraft.class_507.handler$cll000$cracker_util$refresh(class_507.java:4805)
	at net.minecraft.class_507.method_2606(class_507.java)
	at net.minecraft.class_507.method_2592(class_507.java:528)
	at com.tom.storagemod.gui.CraftingTerminalScreen.onUpdateSearch(CraftingTerminalScreen.java:55)
	at com.tom.storagemod.gui.AbstractStorageTerminalScreen.updateSearch(AbstractStorageTerminalScreen.java:250)
	at com.tom.storagemod.gui.AbstractStorageTerminalScreen.method_37432(AbstractStorageTerminalScreen.java:269)
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_37432(CraftingTerminalScreen.java:136)
	at net.minecraft.class_465.method_25393(class_465.java:632)
	at net.minecraft.class_310.method_1572(class_310.java:1821)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_310.method_1574(class_310.java:1821)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

Crash report:
[crash-2023-02-21_13.06.59-client.txt](https://github.com/tom5454/Toms-Storage/files/10793461/crash-2023-02-21_13.06.59-client.txt)

**Comment by WimpieRatte** [comment]
Thank you!
How did you trace it to that mod? (Just out of interest sake - so I can better troubleshoot issues in the future.)
