### ISSUE TITLE
some blocks against inventory trim cause crash

### ISSUE THREAD

**Issue by Trickster29** [tom5454/Toms-Storage#243]
```
java.lang.NullPointerException: Null inventory is not supported.
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at net.fabricmc.fabric.api.transfer.v1.item.InventoryStorage.of(InventoryStorage.java:65)
	at nourl.mythicmetalsdecorations.MythicMetalsDecorations.lambda$registerChestStorage$2(MythicMetalsDecorations.java:70)
	at net.fabricmc.fabric.api.lookup.v1.block.BlockApiLookup.lambda$registerForBlockEntity$0(BlockApiLookup.java:221)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.lambda$registerForBlockEntities$1(BlockApiLookupImpl.java:160)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.find(BlockApiLookupImpl.java:90)
	at com.tom.storagemod.tile.InventoryConnectorBlockEntity.updateServer(InventoryConnectorBlockEntity.java:90)
	at com.tom.storagemod.util.TickerUtil.lambda$createTicker$1(TickerUtil.java:10)
	at net.minecraft.class_2818$class_5563.redirect$zli000$carpet$checkProcessBEs(class_2818.java:789)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:665)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:719)
	at net.minecraft.class_1937.method_18471(class_1937.java:478)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.handler$zlf000$carpet$modifiedRunLoop(MinecraftServer.java:7936)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
to reproduce i put spruce logs against the inventory trim while it was active with a network.

Toms Verision 1.5.7
Fabric

**Comment by tom5454** [comment]
Place a vanilla hopper pointing at the block, to see if it crashes. The error mentions Mythic Metals Decorations, their custom chest handler may be the problem.

**Comment by Trickster29** [comment]
All I did was place a vanilla jungle log. I am unsure why it's mentioned mythic metals. Unless I grabbed the crash report where the mythic metals chest was blocked from above rather than the jungle log report. I did not, that is very weird. However if you just put a try catch statement over your line of code that does nothing this crash would probably just stop. I'd build and change it myself but this seems more complicated to build than other mods. 


Also a hopper has an inventory so thay wouldn't cause the error of course.
