### ISSUE TITLE
Crash when clicking a recipe in crafting terminal

### ISSUE THREAD

**Issue by HylianLZ** [tom5454/Toms-Storage#298]
[latest.log](https://github.com/tom5454/Toms-Storage/files/13222270/latest.log)

I can't figure out what's causing this issue, because I don't know how to read MC logs. It doesn't crash if I use REI to put a recipe in the terminal, nor does it crash if I use a regular crafting table and click a recipe from the book. The recipe I click is in the terminal when I load back in, I just have to lift one item and place it back and I can craft it, but it can't be good to let it crash every time I want to craft something. 

[19:31:00] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[client-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
Caused by: java.lang.ArithmeticException: / by zero
	at net.minecraft.class_514.method_48579(class_514.java:92) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_513.method_2634(class_513.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_507.method_25394(class_507.java:291) ~[client-intermediary.jar:?]
	at com.tom.storagemod.gui.CraftingTerminalScreen.method_25394(CraftingTerminalScreen.java:129) ~[toms_storage_fabric-1.20-1.6.5.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]

**Comment by HylianLZ** [comment]
I think I figured it out. Since I couldn't read the logs properly, I made a copy of my instance and started disabling mods one by one. Turned out to be an incompatibility with [Better Recipe Books](https://www.curseforge.com/minecraft/mc-mods/brb)

**Comment by Pepsied-5229** [comment]
I can confirm with version 1.6.12, Fabric and BRB v1.10.0 RC4. I hope this gets fixed.
