### ISSUE TITLE
Chunks failed to save

### ISSUE THREAD

**Issue by michaelsislow** [tom5454/Toms-Storage#356]
Gonna start by saying im using the mod launcher modrinth. Everytime I use any of the blocks specifically the hopper one it always pops up saying it could not load my chunk and i lose all the items i put inside of it I have confirmed there are no conflicting mods and I have all of the dependencies. Do not know what is going on.

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by michaelsislow** [comment]
[03:19:51] [Server thread/ERROR]:  Failed to save chunk 3,3
java.lang.IllegalStateException: Cannot encode empty ItemStack
	at net.minecraft.class_1799.method_57376(class_1799.java:386) ~[client-intermediary.jar:?]
	at com.tom.storagemod.tile.BasicInventoryHopperBlockEntity.method_11007(BasicInventoryHopperBlockEntity.java:52) ~[toms_storage_fabric-1.20.5-1.6.15.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:113) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:93) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:390) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:330) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:843) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:807) ~[client-intermediary.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1719) ~[fastutil-8.5.12.jar:?]
	at net.minecraft.class_3898.method_17242(class_3898.java:461) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_17298(class_3215.java:304) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_14176(class_3218.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:550) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:574) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_39218(class_1132.java:317) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
