### ISSUE TITLE
Stored amounts display incorrect

### ISSUE THREAD

**Issue by ravensniper72** [tom5454/Toms-Storage#42]
I'm using the 1.17 version of the mod and the displayed amounts of the items in the system are incorrect. They are always higher than what they actually are.

**Comment by vedrit** [comment]
They appear to be doubled, from what I've noticed (Tom's storage v1.1.11, MC 1.17)

**Comment by dustinrouillard** [comment]
Not just doubled. If you use a connector and pull items out with an item pipe of some sort the server/game crashes for this reason.

This only seems to happen with double chests of any kind.

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 6/27/21, 11:38 PM
Description: Exception ticking world

java.lang.IllegalStateException: Tried to extract 64 but we actually extracted 36!
The inventory is now in an invalid (duped) state!

from A = alexiil.mc.lib.attributes.item.impl.GroupedItemInvFixedWrapper@26f98b78
to B = alexiil.mc.lib.attributes.item.impl.GroupedItemInvFixedWrapper@57b1c847
filter C = alexiil.mc.lib.attributes.item.filter.AggregateItemFilter@eb481052
originally extracted = 64 iron_ore
really extracted = 36 iron_ore
        at alexiil.mc.lib.attributes.item.ItemInvUtil.throwBadImplException(ItemInvUtil.java:254)
        at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:130)
        at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:91)
        at me.steven.indrev.networks.item.ItemNetwork.tickRetriever(ItemNetwork.java:103)
        at me.steven.indrev.networks.item.ItemNetwork.tick(ItemNetwork.java:63)
        at me.steven.indrev.networks.NetworkState.tick(NetworkState.java:53)
        at me.steven.indrev.networks.ServoNetworkState.tick(ServoNetworkState.java:28)
        at me.steven.indrev.networks.NetworkEvents.onEndTick(NetworkEvents.java:15)
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$3155/0x00000000cf138260.onEndTick(Unknown Source)
        at net.minecraft.class_1937.handler$bgc000$tickWorldAfterBlockEntities(class_1937.java:4594)
        at net.minecraft.class_1937.method_18471(class_1937.java:479)
        at net.minecraft.class_3218.method_18765(class_3218.java:423)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
        at net.minecraft.class_3176.method_3813(class_3176.java:334)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
        at net.minecraft.server.MinecraftServer$$Lambda$6328/0x00000000a81663f0.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:853)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at alexiil.mc.lib.attributes.item.ItemInvUtil.throwBadImplException(ItemInvUtil.java:254)
        at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:130)
        at alexiil.mc.lib.attributes.item.ItemInvUtil.move(ItemInvUtil.java:91)
        at me.steven.indrev.networks.item.ItemNetwork.tickRetriever(ItemNetwork.java:103)
        at me.steven.indrev.networks.item.ItemNetwork.tick(ItemNetwork.java:63)
        at me.steven.indrev.networks.NetworkState.tick(NetworkState.java:53)
        at me.steven.indrev.networks.ServoNetworkState.tick(ServoNetworkState.java:28)
        at me.steven.indrev.networks.NetworkEvents.onEndTick(NetworkEvents.java:15)
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$3155/0x00000000cf138260.onEndTick(Unknown Source)
        at net.minecraft.class_1937.handler$bgc000$tickWorldAfterBlockEntities(class_1937.java:4594)
        at net.minecraft.class_1937.method_18471(class_1937.java:479)
        at net.minecraft.class_3218.method_18765(class_3218.java:423)
```

Tried this with modded double chests and the vanilla double chest, happens with anything in the chest when pulling out using a pipe obviously.

However, this does not happen when pulling items out of a storage terminal manually it shows the wrong number but when shift-clicking it out you only get the actual amount vs what is shown.

**Comment by dustinrouillard** [comment]
Also possible to completely halt the server when using something else to get items out, because the crash I reported above is actually from Industrial Revolution's dupe protection with the item pipes.
