### ISSUE TITLE
Crash When Accessing Terminal On Server - Fabric 1.21.4-2.1.3

### ISSUE THREAD

**Issue by connorI55** [tom5454/Toms-Storage#510]
I tried my mod pack in single player with no issue. When I try this mod with a server, my game crashes with the following network error.

I have the mod installed on my server, but I may be missing something. Using fabric mod version 1.21.4-2.1.3

`---- Minecraft Network Protocol Error Report ----
// Too many suspicious packets

Time: 2024-12-30 21:54:56
Description: Packet handling error

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at knot//net.minecraft.class_2371.get(class_2371.java:47)
	at knot//net.minecraft.class_1703.method_7611(class_1703.java:313)
	at knot//net.minecraft.class_1703.method_7610(class_1703.java:642)
	at knot//net.minecraft.class_634.method_11153(class_634.java:1355)
	at knot//net.minecraft.class_2649.method_11439(class_2649.java:51)
	at knot//net.minecraft.class_2649.method_65081(class_2649.java:12)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1296)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at knot//net.minecraft.class_2371.get(class_2371.java:47)
	at knot//net.minecraft.class_1703.method_7611(class_1703.java:313)
	at knot//net.minecraft.class_1703.method_7610(class_1703.java:642)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:container_set_content
	Is Terminal: false
	Is Skippable: false
Stacktrace:
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:56)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:131)
	at knot//net.minecraft.class_8673.method_59807(class_8673.java:110)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:32)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:164)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:138)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:123)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1296)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Is Local: false
	Server type: OTHER
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1982269536 bytes (1890 MiB) / 3707764736 bytes (3536 MiB) up to 25165824000 bytes (24000 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 10240.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6636
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 64436.04
	Virtual memory used (MiB): 25999.90
	Swap memory total (MiB): 31744.00
	Swap memory used (MiB): 104.74
	Space in storage for jna.tmpdir (MiB): available: 265807.94, total: 952513.06
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 265807.94, total: 952513.06
	Space in storage for io.netty.native.workdir (MiB): available: 265807.94, total: 952513.06
	Space in storage for java.io.tmpdir (MiB): available: 265807.94, total: 952513.06
	Space in storage for workdir (MiB): available: 265807.94, total: 952513.06
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx24000m -Xms256m
	Fabric Mods: 
		advancementscreenshot: Advancement Screenshot 4.9
		alllootdrops: All Loot Drops 3.4
		alternativeworldsavelocation: Alternative World Save Location 3.6
		alwaysawitherskull: Always a Wither Skull 3.5
		ambientsounds: AmbientSounds 6.1.3
		anvilrestoration: Anvil Restoration 2.3
		aprilfools: April Fools 1.5
		architectury: Architectury 15.0.1
		areas: Areas 6.0
		automaticdoors: Automatic Doors 4.8
		balm-fabric: Balm 21.4.5
			kuma_api: KumaAPI 21.4.4
		barebackhorseriding: Bareback Horse Riding 2.2
		beautifiedchatclient: Beautified Chat Client 2.6
		betterbeaconplacement: Better Beacon Placement 3.4
		betterconduitplacement: Better Conduit Placement 3.3
		betterspawnercontrol: Better Spawner Control 4.6
		biggerspongeabsorptionradius: Bigger Sponge Absorption Radius 3.7
		bobby: Bobby 5.2.6+mc1.21.4
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		boggedspawn: Bogged Spawn 1.1
		bottledair: Bottled Air 2.4
		bottleyourxp: Bottle Your Xp 3.4
		bouncierbeds: Bouncier Beds 2.4
		breedablekillerrabbit: Breedable Killer Rabbit 3.7
		breezespawn: Breeze Spawn 1.1
		campfirespawnandtweaks: Campfire Spawn and Tweaks 3.9
		cavespiderspawn: Cave Spider Spawn 1.2
		clientsort: ClientSort 1.1.1+1.21.3
		cloth-config: Cloth Config v17 17.0.144
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.89
		compacthelpcommand: Compact Help Command 2.7
		conduitspreventdrowned: Conduits Prevent Drowned 3.8
		configurabledespawntimer: Configurable Despawn Timer 4.2
		creativecore: CreativeCore 2.12.22
			net_neoforged_bus: bus 7.2.0
		cryingghasts: Crying Ghasts 3.5
		cryingportals: Crying Portals 2.8
		currentgamemusictrack: Current Game Music Track 2.2
		cyclepaintings: Cycle Paintings 3.6
		cycletitlescreensplash: Cycle Title Screen Splash 1.3
		deathbackup: Death Backup 3.4
		despawningeggshatch: Despawning Eggs Hatch 4.4
		dismountentity: Dismount Entity 3.5
		doubledoors: Double Doors 6.0
		dragondropselytra: Dragon Drops Elytra 3.4
		easyelevators: Easy Elevators 1.2
		easyelytratakeoff: Easy Elytra Takeoff 4.4
		edibles: Edibles 4.4
		enchantingcommands: Enchanting Commands 3.4
		endportalrecipe: End Portal Recipe 5.6
		erodingstoneentities: Eroding Stone Entities 4.6
		extendedbonemeal: Extended Bone Meal 3.5
		extractpoison: Extract Poison 3.4
		fabric-api: Fabric API 0.113.0+1.21.4
			fabric-api-base: Fabric API Base 0.4.54+b47eab6b04
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.86+b1caf1e904
			fabric-biome-api-v1: Fabric Biome API (v1) 15.0.5+b1caf1e904
			fabric-block-api-v1: Fabric Block API (v1) 1.0.31+7feeb73304
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.19+7feeb73304
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.8+7feeb73304
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.29+20ea1e2304
			fabric-command-api-v1: Fabric Command API (v1) 1.2.62+f71b366f04
			fabric-command-api-v2: Fabric Command API (v2) 2.2.41+e496eb1504
			fabric-commands-v0: Fabric Commands (v0) 0.2.79+df3654b304
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.14+7feeb73304
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.10+7f945d5b04
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.10.0+cbf6036a04
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.6+7feeb73304
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.6+9aea556b04
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 22.2.3+20ea1e2304
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.10+7feeb73304
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.12+60fccc7604
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.2+a4eebcf004
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.62+7feeb73304
			fabric-item-api-v1: Fabric Item API (v1) 11.1.14+203e6b2304
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.23+7feeb73304
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.56+7feeb73304
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.54+df3654b304
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.4+bf2a60eb04
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.33+3f89f5a504
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.21+203e6b2304
			fabric-message-api-v1: Fabric Message API (v1) 6.0.25+7feeb73304
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 4.2.0+8ca2ae8d04
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.9+cc0fa2fe04
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 18.0.8+d70d2c0604
			fabric-particles-v1: Fabric Particles (v1) 4.0.14+7feeb73304
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.0.5+b1caf1e904
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.2+3d1fb53904
			fabric-renderer-api-v1: Fabric Renderer API (v1) 5.0.2+84404cdd04
			fabric-renderer-indigo: Fabric Renderer - Indigo 2.0.2+84404cdd04
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.57+73761d2e04
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.19+7feeb73304
			fabric-rendering-v1: Fabric Rendering (v1) 10.1.2+b874120c04
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.13+203e6b2304
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.11+b1caf1e904
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.38+7feeb73304
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.109+7feeb73304
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.32+7feeb73304
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.2+20ea1e2304
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.9+efa825c904
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.3.2+56e78b9b04
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fallthroughslime: Fall Through Slime 3.4
		fastercrouching: Faster Crouching 2.7
		firespreadtweaks: Fire Spread Tweaks 2.7
		firstjoinmessage: First Join Message 3.6
		fishontheline: Fish On The Line 3.4
		fixedanvilrepaircost: Fixed Anvil Repair Cost 3.4
		flowermimics: Flower Mimics 2.0
		followersteleporttoo: Followers Teleport Too 2.6
		furnacerecycle: Furnace Recycle 2.6
		giantspawn: Giant Spawn 5.2
		globalnarrationtoggle: Global Narration Toggle 1.4
		grabbymobs: Grabby Mobs 1.6
		grassseeds: Grass Seeds 3.3
		grindstonesharpertools: Grindstone Sharper Tools 3.7
		guiclock: GUI Clock 4.6
		guicompass: GUI Compass 4.8
		guifollowers: GUI Followers 3.8
		handoveryouritems: Hand Over Your Items 3.5
		healingcampfire: Healing Campfire 6.1
		hidehands: Hide Hands 4.4
		hoetweaks: Hoe Tweaks 3.5
		huskspawn: Husk Spawn 3.6
		icepreventscropgrowth: Ice Prevents Crop Growth 3.4
		improvedsignediting: Improved Sign Editing 1.4
		infinitetrading: Infinite Trading 4.5
		inventorytotem: Inventory Totem 3.3
		java: OpenJDK 64-Bit Server VM 21
		journeymap: Journeymap 1.21.4-6.0.0-beta.32
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.17-1.21.4
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21.4-SNAPSHOT
		justmobheads: Just Mob Heads 8.4
		justplayerheads: Just Player Heads 4.1
		keepmysoiltilled: Keep My Soil Tilled 2.4
		kelpfertilizer: Kelp Fertilizer 3.3
		milkallthemobs: Milk All The Mobs 3.3
		minecraft: Minecraft 1.21.4
		mineralchance: Mineral Chance 3.7
		modmenu: Mod Menu 13.0.0-beta.1
		mooshroomspawn: Mooshroom Spawn 3.6
		mooshroomtweaks: Mooshroom Tweaks 3.5
		morezombievillagers: More Zombie Villagers 3.6
		mousetweaks: Mouse Tweaks 2.27
		moveboats: Move Boats 3.4
		moveminecarts: Move Minecarts 3.6
		nametagtweaks: Name Tag Tweaks 3.9
		naturallychargedcreepers: Naturally Charged Creepers 3.5
		netherportalspread: Nether Portal Spread 8.3
		noanimaltemptdelay: No Animal Tempt Delay 1.2
		nofeathertrample: No Feather Trample 1.3
		nohostilesaroundcampfire: No Hostiles Around Campfire 7.1
		nutritiousmilk: Nutritious Milk 3.4
		omegamute: Omega Mute 4.2
		orediscoverybroadcast: Ore Discovery Broadcast 2.2
		oreharvester: Ore Harvester 1.4
		overworldpiglins: Overworld Piglins 1.5
		paperbooks: Paper Books 3.6
		passiveendermen: Passive Endermen 4.8
		passiveshield: Passive Shield 3.6
		persistentinventorysearch: Persistent Inventory Search 1.5
		petnames: Pet Names 3.4
		piglinnames: Piglin Names 1.1
		placeholder-api: Placeholder API 2.5.1+1.21.3
		pumpkillagersquest: Pumpkillager's Quest 4.4
		quickpaths: Quick Paths 3.5
		quickrightclick: Quick Right-Click 1.5
		rainbegoneritual: Rain Be Gone Ritual 3.4
		randombonemealflowers: Random Bone Meal Flowers 4.6
		randomsheepcolours: Random Sheep Colours 3.4
		randomshulkercolours: Random Shulker Colours 3.3
		randomvillagenames: Random Village Names 3.7
		realisticbees: Realistic Bees 4.0
		recast: Recast 3.5
		recipecommands: Recipe Commands 3.5
		replantingcrops: Replanting Crops 5.4
		respawningshulkers: Respawning Shulkers 4.0
		scaffoldingdropsnearby: Scaffolding Drops Nearby 3.3
		setworldspawnpoint: Set World Spawn Point 3.4
		shulkerdropstwo: Shulker Drops Two 3.4
		simplemenu: Simple Menu 1.5
		skeletonhorsespawn: Skeleton Horse Spawn 4.0
		sleepsooner: Sleep Sooner 4.6
		smallernetherportals: Smaller Nether Portals 3.8
		snowballsfreezemobs: Snowballs Freeze Mobs 3.7
		softerhaybales: Softer Hay Bales 3.3
		sound_physics_remastered: Sound Physics Remastered 1.21.4-1.4.8
		spidersproducewebs: Spiders Produce Webs 3.5
		stackrefill: Stack Refill 4.5
		starterkit: Starter Kit 7.1
		stickyenchantinglapis: Sticky Enchanting Lapis 1.3
		strayspawn: Stray Spawn 3.7
		superflatworldnoslimes: Superflat World No Slimes 3.4
		surfacemushrooms: Surface Mushrooms 3.5
		thornybushprotection: Thorny Bush Protection 1.4
		tntbreaksbedrock: TNT Breaks Bedrock 3.4
		toms_storage: Tom's Simple Storage Mod 2.1.3
		transcendingtrident: Transcending Trident 4.8
		treeharvester: Tree Harvester 9.0
		underwaterenchanting: Underwater Enchanting 2.9
		vanillazoom: Vanilla Zoom 2.7
		villagebellrecipe: Village Bell Recipe 3.7
		villagerdeathmessages: Villager Death Messages 3.5
		villagernames: Villager Names 8.1
		villagespawnpoint: Village Spawn Point 4.4
		voicechat: Simple Voice Chat 1.21.4-2.5.27
		waystones: Waystones 21.4.1
		weakerspiderwebs: Weaker Spiderwebs 3.7
		wooltweaks: Wool Tweaks 3.8
		youritemsaresafe: Your Items Are Safe 4.5
		zombiehorsespawn: Zombie Horse Spawn 5.1
		zombieproofdoors: Zombie Proof Doors 3.4
		zombievillagersfromspawner: Zombie Villagers From Spawner 3.9`

**Comment by Sorro123** [comment]
Same issue
[disconnect-2025-01-07_03.09.14-client.txt](https://github.com/user-attachments/files/18327143/disconnect-2025-01-07_03.09.14-client.txt)

**Comment by buliwyf42** [comment]
The Culprit is Creative Core. 
I just dropped your LogFile into Chat GPT and this is the output. 

Issue Analysis

The error in your Minecraft crash report is related to a “Packet handling error”, specifically an IndexOutOfBoundsException. The key points in the stack trace are:

java.lang.IndexOutOfBoundsException: Index 37 out of bounds for length 37

This error occurs when the program tries to access an element at index 37 in an ArrayList (or similar data structure) that only has 37 elements (i.e., valid indices are 0–36).

Cause of the Issue
	1.	Mod Conflict or Data Corruption:
	•	The error is triggered in the processing of a clientbound/minecraft:container_set_content packet.
	•	This packet updates inventory content, and the error suggests that the server tried to send more inventory slots than the client expects, possibly due to a mod mismatch or a desync.
	2.	Relevant Mods in Stack Trace:
	•	The crash log mentions Fabric Loader and mods like:
	•	inventoryessentials
	•	creativecore
	•	storagedrawers
	•	These mods affect inventory systems and could be modifying the behavior of inventory containers.
	3.	Fabric Mod Loader and Dependencies:
	•	Mods using Fabric API (e.g., Polymer, Sodium, etc.) could create compatibility issues due to mismatched versions.
	4.	Server and Client Version Mismatch:
	•	The server may have a different mod configuration or inventory size, leading to incompatible data packets.
	5.	Packet Modification Mods:
	•	Mods like Packet Fixer and No Chat Reports alter network traffic, possibly leading to unexpected packet structures.

Solutions

1. Check Mod Compatibility:
	•	Update all mods to their latest versions compatible with Minecraft 1.21.4.
	•	Pay attention to inventory-related mods such as:
	•	inventoryessentials
	•	storagedrawers
	•	creativecore
	•	Check their changelogs for fixes related to inventory handling.

2. Test Without Inventory Mods:
	•	Temporarily disable inventory-related mods and test if the issue persists.

3. Client-Server Sync:
	•	Ensure that the client and server have:
	•	The same Minecraft version.
	•	The same mod versions.
	•	No missing or extra mods.

4. Packet Debugging Tools:
	•	Use a minimal set of mods and then gradually add mods back to identify the culprit.
	•	Install mods like Spark or Spark Profiler to monitor packet handling.

5. Fabric API Compatibility:
	•	Verify the Fabric API version (currently 0.114.0+1.21.4) and update it if needed.

6. Mod-Specific Fixes:
	•	For mods like Polymer and Inventory Essentials, check their configuration files for packet size limits or tweaks.

7. Clear Cache and Config:
	•	Delete the .minecraft/config folder and mod cache to ensure no corrupt settings persist.

Additional Notes

If the issue continues, try switching to a vanilla server or forge-based modpack to check if the problem is tied to Fabric API. If required, report the issue to Fabric API developers or the relevant mod maintainers with this error log.

**Comment by Sorro123** [comment]
Yeah, it was creative core. Thanks!
