### ISSUE TITLE
Incompatibility with Inventory Sorter

### ISSUE THREAD

**Issue by xanthian** [tom5454/Toms-Storage#62]
Causes game to crash when attempting to use the storage/crafting terminals on Toms Simple Storage

[Cross posted on Inventory Sorter git also]

[Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "com.tom.storagemod.tile.TileEntityStorageTerminal.canInteractWith(net.minecraft.class_1657)" because "this.te" is null
	at com.tom.storagemod.gui.ContainerStorageTerminal.method_7597(ContainerStorageTerminal.java:549) ~[tomsstorage-1.1.16.jar:?]
	at net.kyrptonaught.inventorysorter.InventoryHelper.shouldDisplayBtns(InventoryHelper.java:82) ~[InventorySorter-1.8.0-1.17.jar:?]
	at net.minecraft.class_465.handler$zbo000$invsort$init(class_465.java:747) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_465.method_25426(class_465.java:94) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at com.tom.storagemod.gui.GuiStorageTerminalBase.method_25426(GuiStorageTerminalBase.java:128) ~[tomsstorage-1.1.16.jar:?]
	at com.tom.storagemod.gui.GuiStorageTerminal.method_25426(GuiStorageTerminal.java:23) ~[tomsstorage-1.1.16.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:387) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:984) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java:65) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3929.method_17541(class_3929.java:51) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_634.method_17587(class_634.java:985) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3944.method_17591(class_3944.java:37) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3944.method_11054(class_3944.java:11) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]

**Comment by TheRealM18** [comment]
[crash-2021-09-21_16.48.39-client.txt](https://github.com/tom5454/Toms-Storage/files/7205859/crash-2021-09-21_16.48.39-client.txt)
