### ISSUE TITLE
22w16b fabric crash

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [tom5454/Toms-Storage#94]
fabric-api-0.51.2+1.19.jar
cloth-config-6.2.57-fabric .jar
or
cloth-config-7.0.60-fabric.jar
toms_storage_fabric-1.18.2-1.3.0 .jar
Minecraft 22w16b

error
java.lang.NoSuchMethodError: 'net.minecraft.class_5250 net.minecraft.class_2588.method_27695(net.minecraft.class_124[])'
	at com.tom.storagemod.StorageModClient.tooltip(StorageModClient.java:175)
	at com.tom.storagemod.StorageModClient.tooltip(StorageModClient.java:165)
	at com.tom.storagemod.item.ItemPaintKit.method_7851(ItemPaintKit.java:38)
       .......

Mod DOES WORK with
Minecraft 22w15a
fabric-api-0.51.0+1.19.jar

P L E A S E provide solution
cause it's the only and best storage mod for 1.19

regards
daniel

**Comment by tom5454** [comment]
fixed
